;; The first three lines of this file were inserted by DrRacket. They record metadata
;; about the language level of this file in a form that our tools can easily process.
#reader(lib "htdp-beginner-reader.ss" "lang")((modname arithmetic) (read-case-sensitive #t) (teachpacks ()) (htdp-settings #(#t constructor repeating-decimal #f #t none #f () #f)))
(+ 1 2)
(+ 1 (+ 1 (+ 1 1) 2) 3 4 5)

(- 3 2)
(* 3 2)
(/ 3 2)
(abs -1.2)
(ceiling 12.3)
(denominator 1.5)
(exact->inexact 1)
(expt 2 5)
(floor -12.4)
(gcd 234 332)
(log 2.718)
(max 112 113)
(numerator 1.5)
(quotient 10 7)
(remainder 10 7)
(random 123)
(sqr 3)
(tan pi)
(sin 0)
(/ 4 6)
(exact->inexact (/ 4 6))
(sqrt 2)